version: '3.2'

services:
  db:
    image: postgis/postgis:15-3.3-alpine	
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    stop_grace_period: 1m
    ports:
      - "5445:5432"
    extends:
      file: common-services.yml
      service: default
  
  migrations:
    build:
      context: .
      dockerfile: migrations.Dockerfile
    depends_on:
      - db
    extends:
      file: common-services.yml
      service: default
    restart: "no"


networks:
  default:
    name: openpvz


volumes:
  pg_data:
